import type { Character } from "./types";

export const CHARACTERS: Character[] = [
  {
    id: "jon-snow",
    name: "Jon Snow",
    aliases: ["Aegon Targaryen", "The White Wolf", "Lord Crow", "The King in the North", "The Bastard of Winterfell"],
    titles: ["998th Lord Commander of the Night's Watch", "King in the North", "Warden of the North"],
    house: "House Stark",
    affiliations: ["Night's Watch", "Free Folk", "House Targaryen"],
    origin: "Dorne",
    seat: "Winterfell / Castle Black",
    alignment: "Lawful Honor",
    status: "Resurrected",
    actor: "Kit Harington",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Black", eyes: "Dark grey", build: "Lean, athletic swordsman", distinguishing: "Facial scars from Orell's eagle; mortal stab wounds over the heart" },
    biography: [
      "Raised at Winterfell as the bastard son of Eddard Stark, Jon Snow grew up beneath the polite contempt of Lady Catelyn and the long shadow of a name he could never inherit. The truth of his birth — that he was Aegon Targaryen, son of Rhaegar Targaryen and Lyanna Stark, born at the Tower of Joy as Robert's Rebellion ended — was buried by Ned beneath seventeen years of silence, a secret kept so well it warped the entire political destiny of Westeros. Denied land and title, Jon chose the one institution in the Seven Kingdoms where bastardy was no stain: the Night's Watch. At Castle Black he found not glory but a decayed order of thieves and broken men, and under the mentorship of Lord Commander Jeor Mormont he was forged from a sulking green boy into a leader.",
      "His arc beyond the Wall redefined the war that mattered. Sent to infiltrate Mance Rayder's free folk host, he broke his vows with Ygritte, climbed the Wall itself, and returned to defend Castle Black against the wildling assault. Elected the 998th Lord Commander, Jon committed the most radical act of his life: opening the gates to the free folk at Hardhome after watching the Night King raise thousands of dead with a single gesture. For that mercy his own sworn brothers assassinated him in the night — 'For the Watch' — and for that mercy Melisandre pulled him back across the threshold of death.",
      "Released from his vows by death itself, Jon retook Winterfell from Ramsay Bolton in the Battle of the Bastards, was proclaimed King in the North, and bent the knee to Daenerys Targaryen to win her dragons for the Great War. He fought through the Long Night, learned his true name, and watched the woman he loved burn King's Landing. His final act — a dagger into Daenerys's heart as he embraced her in the ashes of the throne room — was the same choice Ned would have made: honor over love, the realm over the self. Exiled once more to the Wall, he rode north beyond it with the free folk, the last secret king of Westeros vanishing into the true North.",
    ],
    quote: "Love is the death of duty.",
    stats: {
      combat: 94, intellect: 72, loyalty: 96, influence: 88, survivability: 91, moralCompass: 95,
      screenTimeMinutes: 433, episodeCount: 62, debutYear: 2011, debutEpisode: "S1E1", namedKills: 18, loreMilestones: 14,
    },
    relationships: [
      { targetId: "ned-stark", kind: "family", note: "Raised as Ned's bastard; in truth his nephew" },
      { targetId: "daenerys-targaryen", kind: "lover", note: "Queen, aunt, and finally his victim" },
      { targetId: "arya-stark", kind: "family", note: "Gave her Needle; the sibling bond that never broke" },
      { targetId: "sansa-stark", kind: "family", note: "Retook Winterfell together; she revealed his exile's mercy" },
      { targetId: "night-king", kind: "enemy", note: "The war he alone saw coming" },
      { targetId: "ygritte", kind: "lover", note: "'You know nothing, Jon Snow'" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Born at the Tower of Joy", description: "Lyanna Stark dies birthing him; Ned claims the boy as his own bastard to shield him from Robert.", pivotal: true },
      { marker: "S1E3", era: "S1 — The Wolf and the Lion", title: "Takes the Black", description: "Swears the Night's Watch oath before a heart tree, choosing the old gods.", pivotal: false },
      { marker: "S3E6", era: "S3 — Red Wedding Era", title: "Climbs the Wall", description: "Scales 700 feet of ice with Ygritte and the free folk.", pivotal: false },
      { marker: "S5E8", era: "S5 — Faith and Fire", title: "Hardhome", description: "Witnesses the Night King's power firsthand; kills a White Walker with Longclaw.", pivotal: true },
      { marker: "S5E10", era: "S5 — Faith and Fire", title: "Assassinated by the Watch", description: "Stabbed by his own officers; Olly delivers the final blow.", pivotal: true },
      { marker: "S6E9", era: "S6 — Winds of Winter", title: "Battle of the Bastards", description: "Defeats Ramsay Bolton; Winterfell returns to the Starks.", pivotal: true },
      { marker: "S8E6", era: "S8 — The Last War", title: "Kills Daenerys", description: "Slays the Dragon Queen in the throne room; exiled to the Wall.", pivotal: true },
    ],
    trivia: [
      "His direwolf Ghost was the runt of the litter, found apart from the others — an albino, like Jon a thing apart.",
      "Longclaw, his Valyrian steel sword, originally belonged to House Mormont for five centuries.",
      "He is one of only two characters confirmed to have killed a White Walker with a sword.",
      "Kit Harington kept Longclaw after the show ended.",
      "Jon never sits the Iron Throne despite having the strongest claim of any living character.",
    ],
    keywords: ["bastard", "wall", "direwolf", "ghost", "longclaw", "resurrection", "targaryen", "stark", "winterfell", "north"],
    sigil: "🐺",
    accent: "cerulean",
  },
  {
    id: "daenerys-targaryen",
    name: "Daenerys Targaryen",
    aliases: ["Dany", "Khaleesi", "Mother of Dragons", "Breaker of Chains", "The Unburnt", "Mhysa", "Stormborn"],
    titles: ["Queen of the Andals and the First Men", "Queen of Meereen", "Khaleesi of the Great Grass Sea", "Lady Regnant of the Seven Kingdoms"],
    house: "House Targaryen",
    affiliations: ["The Crown"],
    origin: "The Crownlands",
    seat: "Dragonstone / Meereen",
    alignment: "Ruthless Ambition",
    status: "Deceased",
    causeOfDeath: "Stabbed by Jon Snow in the throne room of the Red Keep",
    actor: "Emilia Clarke",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Silver-gold", eyes: "Violet (lilac)", build: "Slight, regal bearing", distinguishing: "Immune to fire; classic Valyrian features" },
    biography: [
      "Born on Dragonstone during the greatest storm in living memory — hours after her father Aerys II died on the floor of his own throne room — Daenerys Stormborn began life as a fugitive. Smuggled to Essos and raised by her volatile brother Viserys, she spent her childhood being sold the dream of a homeland she had never seen. At thirteen she became a commodity in that dream, traded to Khal Drogo for an army. What should have destroyed her instead remade her: she learned Dothraki, won Drogo's genuine love, and ended Viserys's reign of petty terror with a single sentence — 'He was no dragon. Fire cannot kill a dragon.'",
      "Drogo's death and the stillbirth of her son Rhaego stripped everything from her except conviction. Walking into his funeral pyre with three petrified dragon eggs, she emerged at dawn unburnt, with Drogon, Rhaegal, and Viserion hatched at her breast — the first dragons in the world in a hundred and fifty years. Her march through Slaver's Bay became the moral centerpiece of her legend: she sacked Astapor by turning the Unsullied on their masters, took Yunkai, and crucified 163 Great Masters of Meereen in answer for 163 slave children nailed to mileposts. Mhysa, the freedmen called her. Mother.",
      "Westeros gave her none of Essos's adoration. She lost Viserion to the Night King, Rhaegal to Euron's scorpions, Jorah to the dead, and Missandei to Cersei's headsman — each loss sanding away her restraint. With King's Landing surrendered and the bells ringing, something nineteen years in the making finally broke: she burned the city street by street with Drogon, killing tens of thousands. Days later, promising Jon Snow they would build the new world together, she died in his arms with his dagger in her heart. Drogon melted the Iron Throne rather than the man who killed her, and carried her body east into legend.",
    ],
    quote: "I will take what is mine with fire and blood.",
    stats: {
      combat: 60, intellect: 78, loyalty: 70, influence: 98, survivability: 84, moralCompass: 48,
      screenTimeMinutes: 396, episodeCount: 62, debutYear: 2011, debutEpisode: "S1E1", namedKills: 31, loreMilestones: 16,
    },
    relationships: [
      { targetId: "jon-snow", kind: "lover", note: "Nephew, ally, and executioner" },
      { targetId: "tyrion-lannister", kind: "ally", note: "Her Hand of the Queen, whose counsel she outgrew" },
      { targetId: "cersei-lannister", kind: "enemy", note: "The queen on the throne she came to take" },
      { targetId: "viserys-targaryen", kind: "family", note: "The brother who sold her, crowned in molten gold" },
      { targetId: "night-king", kind: "enemy", note: "Took Viserion from her at the Frozen Lake" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Born during Robert's Rebellion", description: "Birthed on Dragonstone amid a hurricane as the Targaryen dynasty falls.", pivotal: true },
      { marker: "S1E10", era: "S1 — The Wolf and the Lion", title: "The Dragons Hatch", description: "Walks into Drogo's pyre; emerges unburnt with three dragons.", pivotal: true },
      { marker: "S3E4", era: "S3 — Red Wedding Era", title: "Sack of Astapor", description: "'Dracarys.' Takes the Unsullied and burns the masters.", pivotal: true },
      { marker: "S6E6", era: "S6 — Winds of Winter", title: "Khalasar Reborn", description: "Burns the khals at Vaes Dothrak and claims every Dothraki rider alive.", pivotal: false },
      { marker: "S7E6", era: "S7 — The Great War Begins", title: "Loses Viserion", description: "The Night King spears her child from the sky beyond the Wall.", pivotal: true },
      { marker: "S8E5", era: "S8 — The Last War", title: "The Burning of King's Landing", description: "Razes the surrendered capital with dragonfire.", pivotal: true },
      { marker: "S8E6", era: "S8 — The Last War", title: "Death in the Throne Room", description: "Killed by Jon Snow; Drogon melts the Iron Throne.", pivotal: true },
    ],
    trivia: [
      "She names her dragons for the three men of her early life: Drogo, her brothers Rhaegar and Viserys.",
      "The Dothraki gave her the title 'The Unburnt' after Vaes Dothrak — fire immunity is unique to her even among Targaryens in the show.",
      "Emilia Clarke delivered whole scenes in constructed High Valyrian and Dothraki.",
      "Her full style contains 9+ titles — the longest of any character.",
      "She liberated an estimated 200,000+ slaves across Slaver's Bay.",
    ],
    keywords: ["dragons", "khaleesi", "unburnt", "fire and blood", "meereen", "unsullied", "dothraki", "mad queen", "drogon"],
    sigil: "🐉",
    accent: "blood",
  },
  {
    id: "tyrion-lannister",
    name: "Tyrion Lannister",
    aliases: ["The Imp", "Halfman", "The Little Lion", "Hugor Hill", "The Demon Monkey"],
    titles: ["Hand of the King", "Hand of the Queen", "Master of Coin", "Lord of Casterly Rock"],
    house: "House Lannister",
    affiliations: ["House Targaryen", "The Crown"],
    origin: "The Westerlands",
    seat: "Casterly Rock",
    alignment: "Pragmatic Survivor",
    status: "Alive",
    actor: "Peter Dinklage",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Blond", eyes: "Mismatched green and black (books); green (show)", build: "Dwarf, broad-browed", distinguishing: "Facial scar across nose and cheek from the Blackwater" },
    biography: [
      "Tyrion was born to Westeros's richest house and treated as its cheapest possession. His mother Joanna died birthing him, and Tywin never forgave the trade; Cersei tormented him from the cradle. He answered the world's cruelty with the only weapons it couldn't take: a razor mind and a bottomless appetite for books, wine, and conversation. 'A mind needs books as a sword needs a whetstone' — and his stayed sharper than any blade in the realm.",
      "His finest hour came as acting Hand of the King during Stannis's assault on King's Landing. While Joffrey hid, Tyrion devised the wildfire trap that incinerated the Baratheon fleet and personally led the sortie out the Mud Gate — taking a sword across the face for a city that would never thank him. The realm repaid him with a poisoned chalice: framed for Joffrey's murder at the Purple Wedding, betrayed at trial by Shae, the woman he loved, he demanded trial by combat and watched the Mountain crush Oberyn Martell's skull. The night before his execution, Jaime freed him — and Tyrion detoured through the Tower of the Hand to strangle Shae in his father's bed and put two crossbow bolts through Tywin on the privy.",
      "Smuggled across the Narrow Sea in a crate, he drank and quipped his way to Meereen and offered Daenerys the one thing she lacked: a Lannister's understanding of Westerosi power. As Hand of the Queen he engineered her alliance with Dorne, Highgarden, and the Greyjoy fleet — and then watched every clever plan fail and his queen burn a surrendered city. His last great act was treason in the name of mercy: convincing Jon Snow that love is the death of duty. He ended the series as he began it — the smartest man in the room, Hand to a king nobody chose, quietly rebuilding the world that despised him.",
    ],
    quote: "I drink and I know things.",
    stats: {
      combat: 25, intellect: 98, loyalty: 80, influence: 90, survivability: 88, moralCompass: 74,
      screenTimeMinutes: 482, episodeCount: 67, debutYear: 2011, debutEpisode: "S1E1", namedKills: 4, loreMilestones: 12,
    },
    relationships: [
      { targetId: "tywin-lannister", kind: "killed-by", note: "Killed his father with a crossbow — patricide on the privy" },
      { targetId: "cersei-lannister", kind: "rival", note: "A lifetime of mutual loathing between siblings" },
      { targetId: "jaime-lannister", kind: "family", note: "The only Lannister who ever loved him" },
      { targetId: "daenerys-targaryen", kind: "sworn-to", note: "Hand of the Queen until conscience demanded otherwise" },
      { targetId: "sansa-stark", kind: "spouse", note: "Forced marriage, never consummated; mutual respect endured" },
    ],
    timeline: [
      { marker: "S1E6", era: "S1 — The Wolf and the Lion", title: "Trial by Combat at the Eyrie", description: "Bronn fights for him; he buys his life with wit and gold.", pivotal: false },
      { marker: "S2E9", era: "S2 — Clash of Kings", title: "Battle of the Blackwater", description: "His wildfire gambit saves King's Landing from Stannis.", pivotal: true },
      { marker: "S4E6", era: "S4 — Lion's Fall", title: "'I demand a trial by combat'", description: "His courtroom fury at the realm that always hated him.", pivotal: true },
      { marker: "S4E10", era: "S4 — Lion's Fall", title: "Kills Tywin and Shae", description: "Escapes execution and murders his father before fleeing to Essos.", pivotal: true },
      { marker: "S6E2", era: "S6 — Winds of Winter", title: "Unchains the Dragons", description: "Walks alone into the catacombs of Meereen and frees Rhaegal and Viserion.", pivotal: false },
      { marker: "S8E6", era: "S8 — The Last War", title: "Hand of King Bran", description: "Chooses the new king and serves the realm he saved twice.", pivotal: true },
    ],
    trivia: [
      "Peter Dinklage is the most Emmy-awarded actor of the series (4 wins for the role).",
      "Tyrion appears in more episodes (67) than any other character.",
      "He is one of the very few people to have slapped Joffrey — three times in one scene.",
      "His wildfire plan at Blackwater is the largest single-event kill count by a non-dragon character.",
      "He never learned Jon Snow's true parentage until Bran told the lords at the Dragonpit council.",
    ],
    keywords: ["imp", "wine", "wildfire", "blackwater", "hand of the king", "trial", "casterly rock", "patricide", "wit"],
    sigil: "🦁",
    accent: "amber",
  },
  {
    id: "cersei-lannister",
    name: "Cersei Lannister",
    aliases: ["The Queen Mother", "The Lioness", "Light of the West"],
    titles: ["Queen of the Andals and the First Men", "Queen Regent", "Lady of Casterly Rock", "Protector of the Seven Kingdoms"],
    house: "House Lannister",
    affiliations: ["The Crown", "House Baratheon"],
    origin: "The Westerlands",
    seat: "Casterly Rock / Red Keep",
    alignment: "Ruthless Ambition",
    status: "Deceased",
    causeOfDeath: "Crushed beneath the collapsing Red Keep with Jaime during Daenerys's attack",
    actor: "Lena Headey",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Golden blonde (shorn after the Walk of Atonement)", eyes: "Green", build: "Tall, statuesque", distinguishing: "Cropped hair worn as a crown of defiance after S5" },
    biography: [
      "Cersei of House Lannister spent her whole life learning the lesson her father never meant to teach: that everything denied to her was given to lesser men. Married off to Robert Baratheon to seal the new regime, she endured a drunken king who whispered another woman's name on their wedding night — and answered with the most dangerous secret in Westeros, a lifelong incestuous love with her twin Jaime that fathered all three of her children. A woods witch's prophecy haunted her from childhood: queen she would be, until a younger, more beautiful queen cast her down — and gold shrouds for all three of her children.",
      "The prophecy hunted her methodically. Joffrey poisoned at his own wedding. Myrcella poisoned in her arms at sea. Tommen stepping from a window after Cersei's wildfire masterstroke vaporized the Sept of Baelor with Margaery, the High Sparrow, and half the court inside it. By then she had endured the Walk of Atonement — stripped, shorn, and marched naked through the jeering capital — and the woman who climbed the steps of the Red Keep afterward had nothing left to lose and a throne with no one left to contest it. She crowned herself the first ruling Queen of the Andals in Westerosi history.",
      "Her reign was siege warfare against arithmetic. She bought the Golden Company, lured Euron's fleet to her bed and her cause, and executed Missandei on the walls as her last negotiation. None of it mattered against dragons. As King's Landing burned, her armies dissolving, she walked down through the dying castle into Jaime's arms — and the twins who came into the world together left it together, beneath the collapsing crypts of the keep their family had schemed for decades to hold.",
    ],
    quote: "When you play the game of thrones, you win or you die. There is no middle ground.",
    stats: {
      combat: 15, intellect: 84, loyalty: 55, influence: 95, survivability: 79, moralCompass: 22,
      screenTimeMinutes: 350, episodeCount: 62, debutYear: 2011, debutEpisode: "S1E1", namedKills: 11, loreMilestones: 11,
    },
    relationships: [
      { targetId: "jaime-lannister", kind: "lover", note: "Twin, lover, and the arms she died in" },
      { targetId: "tyrion-lannister", kind: "rival", note: "Blamed him for their mother's death his entire life" },
      { targetId: "joffrey-baratheon", kind: "family", note: "Her firstborn — the monster she could never see" },
      { targetId: "tywin-lannister", kind: "family", note: "The father whose approval she chased and never received" },
      { targetId: "daenerys-targaryen", kind: "enemy", note: "The younger queen of the prophecy" },
    ],
    timeline: [
      { marker: "S1E7", era: "S1 — The Wolf and the Lion", title: "Coup Against Ned Stark", description: "Tears Robert's will and seizes the regency for Joffrey.", pivotal: true },
      { marker: "S4E2", era: "S4 — Lion's Fall", title: "The Purple Wedding", description: "Watches Joffrey die in her arms; accuses Tyrion.", pivotal: true },
      { marker: "S5E10", era: "S5 — Faith and Fire", title: "Walk of Atonement", description: "'Shame. Shame. Shame.' Marched naked through King's Landing.", pivotal: true },
      { marker: "S6E10", era: "S6 — Winds of Winter", title: "Destruction of the Sept of Baelor", description: "Wildfire annihilates her enemies; Tommen's suicide follows; she takes the throne.", pivotal: true },
      { marker: "S8E5", era: "S8 — The Last War", title: "Death Beneath the Red Keep", description: "Dies with Jaime as the castle falls.", pivotal: true },
    ],
    trivia: [
      "Lena Headey used a body double for the Walk of Atonement, with 200 extras over three days of filming.",
      "Cersei is the only self-crowned ruling queen in the show's continuity.",
      "Her wine glass is so iconic it became its own internet meme taxonomy.",
      "The valonqar ('little brother') clause of the prophecy was cut from the show — book Cersei fears Tyrion will kill her.",
      "She outlived every member of her immediate family except Tyrion and Jaime — and Jaime only by minutes.",
    ],
    keywords: ["queen", "wildfire", "prophecy", "walk of shame", "twins", "incest", "sept of baelor", "wine", "lioness"],
    sigil: "👑",
    accent: "amber",
  },
  {
    id: "jaime-lannister",
    name: "Jaime Lannister",
    aliases: ["The Kingslayer", "The Young Lion", "Goldenhand"],
    titles: ["Ser", "Lord Commander of the Kingsguard", "Warden of the West"],
    house: "House Lannister",
    affiliations: ["The Crown"],
    origin: "The Westerlands",
    seat: "Casterly Rock",
    alignment: "Pragmatic Survivor",
    status: "Deceased",
    causeOfDeath: "Crushed with Cersei beneath the Red Keep",
    actor: "Nikolaj Coster-Waldau",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Golden blonde", eyes: "Green", build: "Tall, knightly", distinguishing: "Golden prosthetic right hand after Locke's maiming" },
    biography: [
      "Jaime Lannister was the youngest knight ever named to the Kingsguard — and the most reviled. At seventeen, sworn to protect King Aerys II, he listened for months as the Mad King burned men alive, and at the sack of King's Landing he heard the order that broke his oath: burn the city, kill them all. Jaime opened the king's throat instead and saved half a million people, then sat on the Iron Throne to wait, smirking, because the truth was unbearable and contempt was easier. 'Kingslayer' followed him for the rest of his life; he told the real story only once, in a bathtub at Harrenhal, to Brienne of Tarth.",
      "The man who shoved Bran Stark from a tower window in the show's first episode — 'the things I do for love' — spent the rest of the series being painfully reassembled into someone better. Captured by Robb Stark, freed by Catelyn, maimed by Locke, he lost his sword hand and discovered it had been his entire identity. Brienne became his conscience: he leapt one-handed into a bear pit for her, armed her with Oathkeeper (forged from Ned Stark's own greatsword), and sent her to fulfill the oath to Catelyn he could not keep himself.",
      "When Cersei refused to honor the pledge to fight the dead, Jaime rode north alone — the Kingslayer arriving at Winterfell to face the family of the boy he crippled. He fought the Long Night in the ranks, knighted Brienne in the great hall in the series' most tender scene, and then proved redemption is not a straight line: he left her weeping in Winterfell to die where he had always known he would, in the arms of the woman he came into the world beside. 'The things we do for love' — the line that opened his story closed it.",
    ],
    quote: "There are no men like me. Only me.",
    stats: {
      combat: 90, intellect: 70, loyalty: 78, influence: 75, survivability: 76, moralCompass: 60,
      screenTimeMinutes: 230, episodeCount: 55, debutYear: 2011, debutEpisode: "S1E1", namedKills: 15, loreMilestones: 10,
    },
    relationships: [
      { targetId: "cersei-lannister", kind: "lover", note: "Twin and lifelong lover; died together" },
      { targetId: "brienne-of-tarth", kind: "ally", note: "The knight who rebuilt his honor; he knighted her" },
      { targetId: "tyrion-lannister", kind: "family", note: "Freed him from the black cells the night before execution" },
      { targetId: "bran-stark", kind: "enemy", note: "Pushed him from the Broken Tower in S1E1" },
      { targetId: "ned-stark", kind: "rival", note: "Ned found him seated on the throne over Aerys's corpse" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Slays the Mad King", description: "Kills Aerys II to stop the wildfire plot; earns the name Kingslayer.", pivotal: true },
      { marker: "S1E1", era: "S1 — The Wolf and the Lion", title: "Pushes Bran from the Tower", description: "'The things I do for love.'", pivotal: true },
      { marker: "S3E3", era: "S3 — Red Wedding Era", title: "Loses His Sword Hand", description: "Maimed by Locke; his identity severed at the wrist.", pivotal: true },
      { marker: "S4E4", era: "S4 — Lion's Fall", title: "Gives Brienne Oathkeeper", description: "Sends her to find and protect the Stark girls.", pivotal: false },
      { marker: "S8E2", era: "S8 — The Last War", title: "Knights Brienne", description: "'Arise, Brienne of Tarth, a knight of the Seven Kingdoms.'", pivotal: true },
      { marker: "S8E5", era: "S8 — The Last War", title: "Dies with Cersei", description: "The twins die beneath the collapsing Red Keep.", pivotal: true },
    ],
    trivia: [
      "Jaime's golden hand was forged by Qyburn from the gold of Casterly Rock.",
      "He is the only Kingsguard knight in history to kill the king he was sworn to protect.",
      "Nikolaj Coster-Waldau learned to sword-fight left-handed for the post-maiming seasons.",
      "Oathkeeper is one of two swords reforged from Ice, Ned Stark's Valyrian greatsword — the other is Joffrey's Widow's Wail.",
      "His bathtub confession at Harrenhal was filmed in a single extended take.",
    ],
    keywords: ["kingslayer", "golden hand", "kingsguard", "oathkeeper", "redemption", "twins", "harrenhal"],
    sigil: "⚔️",
    accent: "amber",
  },
  {
    id: "arya-stark",
    name: "Arya Stark",
    aliases: ["Arya Horseface", "Arry", "No One", "Cat of the Canals", "The Night Wolf", "Lanna"],
    titles: ["Princess of Winterfell", "Faceless Apprentice"],
    house: "House Stark",
    affiliations: ["Faceless Men", "Brotherhood Without Banners"],
    origin: "The North",
    seat: "Winterfell",
    alignment: "Vengeful Justice",
    status: "Alive",
    actor: "Maisie Williams",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Brown", eyes: "Grey", build: "Small, water-dancer agile", distinguishing: "Abdominal scars from the Waif's knife; carries Needle and a Valyrian steel dagger" },
    biography: [
      "Arya Stark never wanted to be a lady. While Sansa stitched, Arya shot arrows over her brother's shoulder, and Ned — wiser than the customs he upheld — gave her a 'dancing master,' the Braavosi swordsman Syrio Forel, whose lessons ('What do we say to the god of death? Not today.') would carry her through every horror that followed. From the crowd beneath the Sept of Baelor she watched her father beheaded, and the girl who escaped King's Landing that day began composing the most famous prayer in Westeros: a nightly list of names. Joffrey. Cersei. Walder Frey. The Mountain. The Hound.",
      "Her education in death was an odyssey through the war's underbelly: a prisoner at Harrenhal serving Tywin Lannister himself, hostage and reluctant companion to the Hound, arriving at the Twins minutes after the Red Wedding to see her brother's body desecrated. Crossing to Braavos with the iron coin Jaqen H'ghar gave her — valar morghulis — she trained at the House of Black and White to become No One: blind, beaten, serving the Many-Faced God. But the Faceless Men's final lesson was the one she rejected. A girl is Arya Stark of Winterfell, and she was going home.",
      "Her homecoming was the prayer answered. She baked Walder Frey's sons into a pie and slit his throat wearing a servant's face, then poisoned every Frey man who held a blade at the Red Wedding in a single toast. At Winterfell she executed Littlefinger after the trial that finally united her and Sansa. And in the godswood, with the world's last hope dying around her, she did the impossible: leapt at the Night King and put the Valyrian dagger meant for Bran into the dark. The deadliest assassin in the world ended the Long Night, then chose the only frontier left — sailing west of Westeros, off every map ever drawn.",
    ],
    quote: "A girl is Arya Stark of Winterfell. And I'm going home.",
    stats: {
      combat: 95, intellect: 82, loyalty: 90, influence: 50, survivability: 96, moralCompass: 65,
      screenTimeMinutes: 287, episodeCount: 59, debutYear: 2011, debutEpisode: "S1E1", namedKills: 60, loreMilestones: 13,
    },
    relationships: [
      { targetId: "ned-stark", kind: "family", note: "Watched his execution from the crowd" },
      { targetId: "jon-snow", kind: "family", note: "Needle was his gift; the bond that defined them both" },
      { targetId: "sansa-stark", kind: "family", note: "From rivalry to the partnership that destroyed Littlefinger" },
      { targetId: "the-hound", kind: "mentor", note: "Captor turned reluctant teacher; she left him to die, then forgave him" },
      { targetId: "night-king", kind: "killer-of", note: "Ended the Long Night with the catspaw dagger" },
      { targetId: "petyr-baelish", kind: "killer-of", note: "Executed him with his own dagger after Sansa's sentence" },
    ],
    timeline: [
      { marker: "S1E9", era: "S1 — The Wolf and the Lion", title: "Witnesses Ned's Execution", description: "The list of names begins.", pivotal: true },
      { marker: "S3E9", era: "S3 — Red Wedding Era", title: "Arrives at the Red Wedding", description: "Reaches the Twins as her family is slaughtered inside.", pivotal: true },
      { marker: "S5E2", era: "S5 — Faith and Fire", title: "The House of Black and White", description: "Begins Faceless training in Braavos.", pivotal: false },
      { marker: "S6E10", era: "S6 — Winds of Winter", title: "Kills Walder Frey", description: "Frey pie, a borrowed face, and a cut throat.", pivotal: true },
      { marker: "S8E3", era: "S8 — The Last War", title: "Kills the Night King", description: "The dagger drop heard around the world; the dead fall.", pivotal: true },
      { marker: "S8E6", era: "S8 — The Last War", title: "Sails West of Westeros", description: "Leaves the known world behind.", pivotal: true },
    ],
    trivia: [
      "Her sword Needle is the only physical object that survives her entire journey from S1E2 to the finale.",
      "Arya has the highest named kill count of any non-dragon character.",
      "Maisie Williams is right-handed but learned to fight left-handed because book-Arya is a lefty.",
      "The catspaw Valyrian dagger she kills the Night King with is the same blade sent to assassinate Bran in Season 1.",
      "Her kill of the Night King was planned by the showrunners three years before it aired.",
    ],
    keywords: ["needle", "faceless men", "valar morghulis", "list", "assassin", "braavos", "no one", "night king", "stark"],
    sigil: "🗡️",
    accent: "cerulean",
  },
  {
    id: "sansa-stark",
    name: "Sansa Stark",
    aliases: ["The Little Bird", "Alayne Stone", "The Lady of Winterfell", "The Red Wolf"],
    titles: ["Queen in the North", "Lady of Winterfell"],
    house: "House Stark",
    affiliations: ["House Lannister", "House Bolton"],
    origin: "The North",
    seat: "Winterfell",
    alignment: "Pragmatic Survivor",
    status: "Alive",
    actor: "Sophie Turner",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Auburn (Tully red)", eyes: "Blue", build: "Tall, graceful", distinguishing: "Inherited Catelyn's Tully coloring; designs and sews her own armor-influenced gowns" },
    biography: [
      "Sansa Stark began the series as its most conventional dreamer — a girl raised on songs who believed in golden princes, and whose wish to marry Joffrey Baratheon came true as a curse. King's Landing was her education in everything the songs omitted: her father's head on a spike that Joffrey forced her to look at, beatings administered by Kingsguard knights at a king's command, survival measured out one courtesy at a time. 'The little bird,' the Hound called her, and the cage kept changing hands — from Joffrey to the Tyrells' marriage schemes to a forced wedding with Tyrion Lannister, the only captor who treated her with decency.",
      "Littlefinger's extraction of her after the Purple Wedding traded one predator for a subtler one. As 'Alayne Stone' in the Vale she watched him murder her aunt Lysa and learned the grammar of manipulation from its finest practitioner — and then he sold her to the Boltons. Her marriage to Ramsay was the darkest chapter of her life, and her escape from Winterfell with Theon, leaping from the castle walls into the snow, was its turning point. She found Jon at Castle Black, and it was Sansa — writing secretly to the Vale — whose Knights arrived to win the Battle of the Bastards. She fed Ramsay to his own hounds and did not look away.",
      "What emerged at Winterfell was the truest student of every monster who ever held her: Cersei's ruthlessness without the cruelty, Littlefinger's perception without the treachery. She out-positioned Baelish until he knelt begging in her own hall, ran the North's logistics through the Long Night, and refused to let Northern independence die at the bargaining table — extracting from the Six Kingdoms' new order the one thing her family had bled for across eight seasons. Crowned Queen in the North in the finale, the little bird ended the series as the only player who got everything she actually wanted.",
    ],
    quote: "I'm a slow learner, it's true. But I learn.",
    stats: {
      combat: 12, intellect: 88, loyalty: 85, influence: 86, survivability: 90, moralCompass: 78,
      screenTimeMinutes: 263, episodeCount: 59, debutYear: 2011, debutEpisode: "S1E1", namedKills: 2, loreMilestones: 11,
    },
    relationships: [
      { targetId: "ned-stark", kind: "family", note: "Her plea for Joffrey's mercy could not save him" },
      { targetId: "petyr-baelish", kind: "enemy", note: "Mentor in manipulation; she sentenced him to death" },
      { targetId: "tyrion-lannister", kind: "spouse", note: "The kindest of her captivities" },
      { targetId: "ramsay-bolton", kind: "killed-by", note: "She fed him to his own starving hounds" },
      { targetId: "arya-stark", kind: "family", note: "Judge and executioner — together — at Littlefinger's trial" },
      { targetId: "jon-snow", kind: "family", note: "Reunited at Castle Black; she secured the Vale's cavalry for his battle" },
    ],
    timeline: [
      { marker: "S1E9", era: "S1 — The Wolf and the Lion", title: "Hostage of the Crown", description: "Ned's execution turns her betrothal into captivity.", pivotal: true },
      { marker: "S3E8", era: "S3 — Red Wedding Era", title: "Wed to Tyrion", description: "A Lannister marriage forced on both parties.", pivotal: false },
      { marker: "S5E6", era: "S5 — Faith and Fire", title: "Married to Ramsay Bolton", description: "Sold by Littlefinger into the series' cruelest household.", pivotal: true },
      { marker: "S6E9", era: "S6 — Winds of Winter", title: "Battle of the Bastards", description: "Her secret letter brings the Vale; Ramsay's hounds get their supper.", pivotal: true },
      { marker: "S7E7", era: "S7 — The Great War Begins", title: "Trial of Littlefinger", description: "'You're a slow learner.' Petyr Baelish dies in her hall.", pivotal: true },
      { marker: "S8E6", era: "S8 — The Last War", title: "Crowned Queen in the North", description: "Wins independence for the North; the only sovereign demand granted.", pivotal: true },
    ],
    trivia: [
      "Sophie Turner adopted Zunni, the dog who played Sansa's direwolf Lady.",
      "Her S8 coronation gown was embroidered with weirwood leaves and a direwolf clasp — every costume detail tracked her arc.",
      "She is one of only two surviving Stark children to hold Winterfell at series end.",
      "Sansa's hairstyles deliberately mimicked whoever held power over her — Cersei's curls, Margaery's braids — until she chose her own.",
      "She is the only main character to interact closely with Joffrey, Cersei, Littlefinger, AND Ramsay and survive all four.",
    ],
    keywords: ["little bird", "winterfell", "queen in the north", "vale", "alayne", "survivor", "politics", "tully"],
    sigil: "🕊️",
    accent: "verdant",
  },
  {
    id: "ned-stark",
    name: "Eddard Stark",
    aliases: ["Ned", "The Quiet Wolf"],
    titles: ["Lord of Winterfell", "Warden of the North", "Hand of the King"],
    house: "House Stark",
    affiliations: ["The Crown"],
    origin: "The North",
    seat: "Winterfell",
    alignment: "Lawful Honor",
    status: "Deceased",
    causeOfDeath: "Beheaded with his own sword, Ice, on Joffrey's order at the Sept of Baelor",
    actor: "Sean Bean",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Dark brown", eyes: "Grey", build: "Solid, weathered northern lord", distinguishing: "Carried the Valyrian greatsword Ice; long face of the Starks" },
    biography: [
      "Eddard Stark was the second son never meant to rule. Fostered at the Eyrie alongside Robert Baratheon under Jon Arryn, he inherited Winterfell only because the Mad King burned his father alive and strangled his brother Brandon in the throne room — the atrocity that ignited Robert's Rebellion. Ned fought the war at Robert's side, fought the Kingsguard's finest at the Tower of Joy, and came home with his sister Lyanna's bones and a black-haired infant he called his bastard. The lie cost him his wife's trust at the edges and his honor's comfort at the core, and he carried it without complaint for seventeen years, because the truth would have meant the baby's death.",
      "His fatal promotion came when Jon Arryn died suddenly and Robert rode north to make Ned his Hand. King's Landing was a game he refused to learn: he investigated Arryn's death honestly, deduced from Baratheon bloodlines what Arryn had died for knowing — that Cersei's children were Jaime's — and then committed the most catastrophic act of mercy in the series, warning Cersei to flee before he told Robert. Robert died of a boar wound greased by Lannister wine; Ned's attempt to enforce the true succession died when Littlefinger's gold cloaks turned and a dagger touched his throat in his own moment of triumph.",
      "His execution rewrote television. Forced into a false confession to protect Sansa, promised mercy and the Wall, he was beheaded on the steps of the Sept of Baelor at the whim of the boy-king — the moment the audience learned that this story killed its heroes. Yet Ned won the long game from the grave: every surviving Stark navigated the wars by his code, his secret preserved the trueborn heir of two dynasties, and the pack he raised — 'the lone wolf dies, but the pack survives' — ended the series holding the North, the Six Kingdoms' throne, and the gratitude of the living world.",
    ],
    quote: "The man who passes the sentence should swing the sword.",
    stats: {
      combat: 82, intellect: 65, loyalty: 99, influence: 80, survivability: 30, moralCompass: 99,
      screenTimeMinutes: 137, episodeCount: 10, debutYear: 2011, debutEpisode: "S1E1", namedKills: 6, loreMilestones: 9,
    },
    relationships: [
      { targetId: "jon-snow", kind: "family", note: "Claimed his nephew as his bastard to save his life" },
      { targetId: "robb-stark", kind: "family", note: "His heir, who went to war to avenge him" },
      { targetId: "arya-stark", kind: "family", note: "Gave her Syrio Forel instead of a septa" },
      { targetId: "sansa-stark", kind: "family", note: "Confessed falsely to protect her" },
      { targetId: "cersei-lannister", kind: "enemy", note: "His mercy toward her was his death warrant" },
      { targetId: "petyr-baelish", kind: "killed-by", note: "'I did warn you not to trust me.'" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Tower of Joy", description: "Defeats Ser Arthur Dayne's Kingsguard; promises Lyanna to protect her son.", pivotal: true },
      { marker: "S1E1", era: "S1 — The Wolf and the Lion", title: "Named Hand of the King", description: "Robert rides north; the deserter's execution opens the series.", pivotal: true },
      { marker: "S1E7", era: "S1 — The Wolf and the Lion", title: "Betrayed in the Throne Room", description: "The gold cloaks turn; Littlefinger's dagger at his throat.", pivotal: true },
      { marker: "S1E9", era: "S1 — The Wolf and the Lion", title: "Executed at the Sept of Baelor", description: "Joffrey demands his head; the realm shatters.", pivotal: true },
    ],
    trivia: [
      "Sean Bean was the show's top-billed actor — his death in episode 9 was the series' founding shock.",
      "Ice, his greatsword, was melted down into Oathkeeper and Widow's Wail.",
      "The promise to Lyanna — 'promise me, Ned' — is the seed of the entire R+L=J reveal.",
      "He personally executes the Night's Watch deserter in the first episode whose warnings about White Walkers were true.",
      "Despite 10 episodes of screen time, he is referenced in every single season of the show.",
    ],
    keywords: ["honor", "hand of the king", "ice", "winterfell", "execution", "tower of joy", "promise me ned", "warden"],
    sigil: "🌨️",
    accent: "cerulean",
  },
  {
    id: "bran-stark",
    name: "Bran Stark",
    aliases: ["Brandon Stark", "The Three-Eyed Raven", "Bran the Broken", "The Winged Wolf"],
    titles: ["King of the Andals and the First Men", "Lord of the Six Kingdoms", "Prince of Winterfell"],
    house: "House Stark",
    affiliations: ["The Crown"],
    origin: "The North",
    seat: "Winterfell / Red Keep",
    alignment: "Cold Entropy",
    status: "Transformed",
    actor: "Isaac Hempstead Wright",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Auburn-brown", eyes: "Blue", build: "Paralyzed below the waist since S1E1", distinguishing: "Thousand-yard stare of the Three-Eyed Raven; wheeled chair designed by Maester Wolkan" },
    biography: [
      "Bran Stark's story begins with the series' inciting crime: a boy who loved to climb found Jaime and Cersei Lannister together in the Broken Tower, and was pushed from the window to keep the secret. He woke from the coma paralyzed, his memory of the fall gone — and with something new in his dreams, a three-eyed raven leading him north. His coma-vision marked the opening of a door that would never close. While the War of the Five Kings burned, Bran fled Theon's sack of Winterfell with Hodor, Osha, and Rickon, and chose the harder road: not to a brother's army, but beyond the Wall, toward the raven.",
      "The journey consumed nearly everyone who shared it. Jojen Reed died within sight of the weirwood; inside it, the ancient greenseer fused to the tree began teaching Bran to swim through time itself. His education ended in catastrophe — touched by the Night King in a vision, he led the dead straight to the cave, and his escape was paid for by the most devastating time-loop in the series: holding the door, he reached back through decades and broke a stableboy's mind, creating Hodor with the same words that killed him. The boy who entered the cave never left it; what walked out wore his face and carried the memory of the world.",
      "As the Three-Eyed Raven he became the war's living archive and its bait: it was Bran who confirmed Jon's parentage from Howland Reed's hidden history, Bran who waited in the godswood as the Night King came for the memory of mankind, Bran whose calm unsettled every room he entered. At the Dragonpit council, Tyrion's argument — who has a better story? — crowned him King of the Six Kingdoms, the first elected monarch in Westerosi history. Whether Bran the Broken foresaw it all is the show's last deliberate ambiguity: 'Why do you think I came all this way?'",
    ],
    quote: "I'm not Brandon Stark anymore. I'm the Three-Eyed Raven.",
    stats: {
      combat: 5, intellect: 92, loyalty: 60, influence: 85, survivability: 70, moralCompass: 55,
      screenTimeMinutes: 152, episodeCount: 50, debutYear: 2011, debutEpisode: "S1E1", namedKills: 1, loreMilestones: 12,
    },
    relationships: [
      { targetId: "jaime-lannister", kind: "enemy", note: "'The things we do for love' — and later, absolution at Winterfell" },
      { targetId: "night-king", kind: "enemy", note: "Marked by his touch; hunted across the world for his memory" },
      { targetId: "jon-snow", kind: "family", note: "Revealed Jon's true name and claim" },
      { targetId: "tyrion-lannister", kind: "ally", note: "The Hand who crowned him with a story" },
      { targetId: "ned-stark", kind: "family", note: "Witnessed his father's past in greensight visions" },
    ],
    timeline: [
      { marker: "S1E1", era: "S1 — The Wolf and the Lion", title: "The Fall", description: "Pushed from the Broken Tower by Jaime Lannister.", pivotal: true },
      { marker: "S3E5", era: "S3 — Red Wedding Era", title: "Beyond the Wall", description: "Crosses north with Hodor and the Reeds, pursuing the raven.", pivotal: false },
      { marker: "S6E5", era: "S6 — Winds of Winter", title: "Hold the Door", description: "Hodor's origin and death in one impossible moment.", pivotal: true },
      { marker: "S7E3", era: "S7 — The Great War Begins", title: "Returns to Winterfell", description: "The Three-Eyed Raven comes home wearing Bran's face.", pivotal: false },
      { marker: "S8E3", era: "S8 — The Last War", title: "Bait in the Godswood", description: "Waits for the Night King as the Long Night peaks.", pivotal: true },
      { marker: "S8E6", era: "S8 — The Last War", title: "Crowned Bran the Broken", description: "Elected King of the Six Kingdoms at the Dragonpit.", pivotal: true },
    ],
    trivia: [
      "Isaac Hempstead Wright was absent for all of Season 5 — Bran's training montage happened entirely off-screen.",
      "The 'Hold the Door' twist was told to the showrunners directly by George R.R. Martin.",
      "Bran is the first king of Westeros chosen by council rather than conquest or inheritance.",
      "He warged into Summer, ravens, and Hodor — the only confirmed human-into-human warg in the show.",
      "His S8 wheelchair was based on a medieval design from a 1595 engraving.",
    ],
    keywords: ["three-eyed raven", "greensight", "warg", "hodor", "hold the door", "king", "weirwood", "visions"],
    sigil: "👁️",
    accent: "verdant",
  },
  {
    id: "tywin-lannister",
    name: "Tywin Lannister",
    aliases: ["The Great Lion", "The Old Lion"],
    titles: ["Lord of Casterly Rock", "Warden of the West", "Hand of the King (thrice)", "Savior of the City"],
    house: "House Lannister",
    affiliations: ["The Crown"],
    origin: "The Westerlands",
    seat: "Casterly Rock",
    alignment: "Ruthless Ambition",
    status: "Deceased",
    causeOfDeath: "Shot twice with a crossbow by Tyrion while on the privy",
    actor: "Charles Dance",
    firstAppearance: { season: 1, episode: 7, title: "You Win or You Die" },
    physical: { hair: "Bald (formerly gold)", eyes: "Pale green flecked with gold", build: "Tall, imposing, soldier-straight in his sixties", distinguishing: "Side-whiskers; never seen laughing" },
    biography: [
      "Tywin Lannister rebuilt a laughingstock into the most feared name in Westeros. His father Tytos had been a soft lord whom vassals mocked openly; Tywin's answer became a wedding song. When House Reyne of Castamere rose against the Rock, Tywin exterminated them — every man, woman, and child — and 'The Rains of Castamere' was played thereafter so no one would ever need reminding twice. Twenty years as Aerys II's Hand made the realm prosperous and Tywin indispensable, until the Mad King's jealousy and his refusal of Cersei for Prince Rhaegar drove Tywin to resign — and, when the rebellion's outcome was clear, to sack King's Landing under a false banner of friendship and present Robert with the bodies of Rhaegar's children wrapped in Lannister crimson.",
      "The War of the Five Kings was his masterpiece and his blind spot. Introduced skinning a stag — the Baratheon sigil — while dressing down Jaime, he fought Robb Stark to a standstill in the field and then won the war by raven: the Red Wedding was underwritten by Tywin's pen, Walder Frey and Roose Bolton merely the instruments. 'Explain to me why it is more noble to kill ten thousand men in battle than a dozen at dinner.' As Hand to his grandson Joffrey he ruled the Seven Kingdoms in all but name, the only man the boy-king visibly feared.",
      "His empire was annihilated by the son he refused to see. Tywin's lifelong contempt for Tyrion — the dwarf whose birth killed Joanna, the heir he denied Casterly Rock to his face — culminated in sentencing him to death for a murder he knew Tyrion didn't commit. On the night of the escape, Tyrion found Shae in his father's bed and Tywin on the privy, and the great lion died refusing to the last breath to call his son anything but a threat. The Rains of Castamere played over his funeral; within four years, every plan he built had crumbled and the dynasty he murdered thousands to secure was extinct in the male line.",
    ],
    quote: "A lion does not concern himself with the opinions of sheep.",
    stats: {
      combat: 70, intellect: 95, loyalty: 40, influence: 97, survivability: 60, moralCompass: 18,
      screenTimeMinutes: 156, episodeCount: 27, debutYear: 2011, debutEpisode: "S1E7", namedKills: 9, loreMilestones: 10,
    },
    relationships: [
      { targetId: "tyrion-lannister", kind: "killed-by", note: "Two crossbow bolts from the son he disowned" },
      { targetId: "cersei-lannister", kind: "family", note: "Used her as a marriage pawn; she craved his respect" },
      { targetId: "jaime-lannister", kind: "family", note: "His chosen heir, who refused the Rock" },
      { targetId: "robb-stark", kind: "enemy", note: "Defeated him by raven, not by sword" },
      { targetId: "arya-stark", kind: "rival", note: "Unknowingly employed her as his cupbearer at Harrenhal" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "The Rains of Castamere", description: "Exterminates House Reyne; the song becomes a warning.", pivotal: true },
      { marker: "S1E7", era: "S1 — The Wolf and the Lion", title: "Mobilizes the West", description: "Sends Gregor Clegane to ravage the Riverlands.", pivotal: false },
      { marker: "S2E7", era: "S2 — Clash of Kings", title: "Harrenhal", description: "Quarters with an unrecognized Arya Stark as cupbearer.", pivotal: false },
      { marker: "S3E9", era: "S3 — Red Wedding Era", title: "Author of the Red Wedding", description: "'The Lannisters send their regards.'", pivotal: true },
      { marker: "S4E10", era: "S4 — Lion's Fall", title: "Death on the Privy", description: "Killed by Tyrion with Joffrey's crossbow.", pivotal: true },
    ],
    trivia: [
      "Charles Dance really skinned that stag in his introduction scene — he learned field dressing for it.",
      "Tywin served as Hand to three kings: Aerys II, Joffrey, and Tommen (briefly, in name).",
      "He never directly swung a sword on screen despite commanding every major Lannister victory.",
      "The Red Wedding violated guest right — in-world, the gods themselves are said to curse its breakers.",
      "George R.R. Martin has called Tywin one of the series' true villains precisely because he is never gratuitously cruel — only efficient.",
    ],
    keywords: ["castamere", "hand of the king", "red wedding", "casterly rock", "legacy", "lion", "patriarch"],
    sigil: "🏛️",
    accent: "amber",
  },
  {
    id: "petyr-baelish",
    name: "Petyr Baelish",
    aliases: ["Littlefinger"],
    titles: ["Lord of Harrenhal", "Lord Protector of the Vale", "Master of Coin"],
    house: "The Crown",
    affiliations: ["House Tully", "House Stark"],
    origin: "The Vale",
    seat: "Harrenhal / The Eyrie",
    alignment: "Chaotic Schemer",
    status: "Deceased",
    causeOfDeath: "Throat cut by Arya Stark on Sansa's sentence, with his own Valyrian dagger",
    actor: "Aidan Gillen",
    firstAppearance: { season: 1, episode: 3, title: "Lord Snow" },
    physical: { hair: "Dark, silver-templed", eyes: "Grey-green", build: "Slight, immaculate", distinguishing: "Mockingbird pin; a chest scar from Brandon Stark's sword" },
    biography: [
      "Petyr Baelish came from nothing that mattered — a minor lord of the smallest holding on the smallest of the Fingers, fostered at Riverrun where he fell catastrophically in love with Catelyn Tully. When she was betrothed to Brandon Stark, the boy challenged a man twice his size to a duel and was opened from navel to collarbone for it. The scar taught him the lesson that built everything after: he would never win playing by the rules of men born above him. So he changed games. Money, information, and other people's appetites became his weapons; brothels and the realm's ledgers became his armory.",
      "Littlefinger is the single most consequential schemer in the series — virtually every catastrophe traces to his hand. He convinced Lysa Arryn to poison her husband Jon Arryn and blame the Lannisters, the spark of the entire War of the Five Kings. He betrayed Ned Stark in the throne room with a dagger at his throat. He brokered the Tyrell alliance that won the Blackwater, orchestrated Joffrey's poisoning with Olenna Tyrell, spirited Sansa from the capital, pushed Lysa through the Moon Door, and sold Sansa to the Boltons while holding the Vale's army in reserve — arriving at the Battle of the Bastards as savior of the very family he had destroyed. 'Chaos isn't a pit. Chaos is a ladder.'",
      "He died of the one miscalculation his ledger couldn't cover: teaching Sansa Stark everything he knew. His final gambit — turning the Stark sisters against each other in Winterfell — collapsed when the sisters compared notes and Bran's omniscience supplied the evidence. Tried in the hall he schemed decades to rule, his every crime recited back to him, the man who began the War of the Five Kings ended on his knees, begging, before the dagger that started it all opened his throat.",
    ],
    quote: "Chaos isn't a pit. Chaos is a ladder.",
    stats: {
      combat: 20, intellect: 96, loyalty: 5, influence: 92, survivability: 72, moralCompass: 8,
      screenTimeMinutes: 134, episodeCount: 41, debutYear: 2011, debutEpisode: "S1E3", namedKills: 3, loreMilestones: 11,
    },
    relationships: [
      { targetId: "sansa-stark", kind: "apprentice", note: "His student in manipulation — and his judge" },
      { targetId: "ned-stark", kind: "killer-of", note: "His betrayal delivered Ned to the block" },
      { targetId: "arya-stark", kind: "killed-by", note: "Executed with the catspaw dagger he once owned" },
      { targetId: "varys", kind: "rival", note: "The realm's two spymasters, dueling in riddles" },
      { targetId: "joffrey-baratheon", kind: "killer-of", note: "Co-architect of the Purple Wedding poisoning" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Poisons Jon Arryn (by proxy)", description: "Lysa administers the Tears of Lys; the realm blames the Lannisters.", pivotal: true },
      { marker: "S1E7", era: "S1 — The Wolf and the Lion", title: "Betrays Ned Stark", description: "'I did warn you not to trust me.'", pivotal: true },
      { marker: "S4E2", era: "S4 — Lion's Fall", title: "The Purple Wedding", description: "Joffrey dies; the necklace's missing stone sails away with Sansa.", pivotal: true },
      { marker: "S4E7", era: "S4 — Lion's Fall", title: "The Moon Door", description: "'Only Cat.' Pushes Lysa Arryn into the sky.", pivotal: true },
      { marker: "S7E7", era: "S7 — The Great War Begins", title: "Trial at Winterfell", description: "Sansa sentences; Arya executes.", pivotal: true },
    ],
    trivia: [
      "The catspaw dagger that kills him is the same blade he falsely attributed to Tyrion in Season 1 — the lie that ignited the Stark–Lannister war.",
      "Aidan Gillen deliberately shifted Littlefinger's accent across seasons, calling the character 'a performer' whose voice was also a mask.",
      "He is directly or indirectly responsible for the deaths of Jon Arryn, Ned Stark, Joffrey, Lysa Arryn, and Ros.",
      "His mockingbird sigil was self-chosen — he refused his family's modest Titan's head.",
      "Littlefinger's brothel financed an intelligence network second only to Varys's little birds.",
    ],
    keywords: ["littlefinger", "chaos is a ladder", "mockingbird", "master of coin", "betrayal", "schemer", "moon door", "brothel"],
    sigil: "🪜",
    accent: "blood",
  },
  {
    id: "varys",
    name: "Varys",
    aliases: ["The Spider", "The Master of Whisperers", "The Eunuch"],
    titles: ["Master of Whisperers", "Lord (honorific, landless)"],
    house: "The Crown",
    affiliations: ["House Targaryen"],
    origin: "Essos",
    seat: "Red Keep (no lands)",
    alignment: "Pragmatic Survivor",
    status: "Deceased",
    causeOfDeath: "Executed by dragonfire on Daenerys's order for treason",
    actor: "Conleth Hill",
    firstAppearance: { season: 1, episode: 3, title: "Lord Snow" },
    physical: { hair: "Bald", eyes: "Dark", build: "Soft, powdered, deliberately unthreatening", distinguishing: "Flowing robes; moves silently — 'the Spider' walks without sound" },
    biography: [
      "Varys was born a slave in Lyseni obscurity and mutilated as a boy by a sorcerer who burned his parts in a brazier — and heard a voice answer from the flames. The experience left him with a hatred of magic, a terror of fire, and an unmatched understanding of what desperation teaches: he survived the gutters of Myr and Pentos as a thief who stole letters instead of purses, discovering that information outvalues gold everywhere men have secrets. By the time Aerys II summoned him to Westeros, his network of 'little birds' — child informants threaded through every city of two continents — made him the best-informed man alive.",
      "Across five kings he played the same long game he confessed only in riddles: he served not the throne but the realm, the millions who plant crops and pay the blood-price for highborn ambitions. He saved Tyrion twice — testifying nothing at his trial but arranging the crate to Pentos — and steered him to Daenerys, the ruler Varys had spent two decades positioning as the realm's best chance. 'Power resides where men believe it resides. It's a trick, a shadow on the wall.'",
      "His principles finally cost what they had always threatened to. Watching Daenerys harden after Missandei's execution — and knowing now that Jon Snow's claim was better — Varys did what he had done under every monarch who failed his test: he began quietly working toward succession, writing letters about Jon's parentage. Tyrion informed the queen. On the shores of Dragonstone, the man who feared fire above all things removed his rings, met his oldest friend's eyes without rancor — 'I hope I deserve this. Truly, I do. I hope I'm wrong.' — and was unmade by the dragon he helped crown.",
    ],
    quote: "Power resides where men believe it resides.",
    stats: {
      combat: 5, intellect: 94, loyalty: 65, influence: 88, survivability: 75, moralCompass: 70,
      screenTimeMinutes: 130, episodeCount: 46, debutYear: 2011, debutEpisode: "S1E3", namedKills: 1, loreMilestones: 8,
    },
    relationships: [
      { targetId: "tyrion-lannister", kind: "ally", note: "Saved his life; Tyrion reported his final treason" },
      { targetId: "petyr-baelish", kind: "rival", note: "The Spider versus the Mockingbird" },
      { targetId: "daenerys-targaryen", kind: "killed-by", note: "Dracarys, for choosing the realm over the queen" },
      { targetId: "jon-snow", kind: "ally", note: "His last cause: the heir who didn't want the throne" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Cut by the Sorcerer", description: "Mutilated in a blood ritual; hears a voice in the flames.", pivotal: true },
      { marker: "S1E5", era: "S1 — The Wolf and the Lion", title: "The Riddle of Power", description: "Spars with Littlefinger beneath the throne; warns Ned too subtly.", pivotal: false },
      { marker: "S4E10", era: "S4 — Lion's Fall", title: "The Crate to Essos", description: "Smuggles Tyrion out — and steps aboard himself as the bells toll.", pivotal: true },
      { marker: "S8E5", era: "S8 — The Last War", title: "Executed at Dragonstone", description: "Burned for treason he committed with open eyes.", pivotal: true },
    ],
    trivia: [
      "Conleth Hill is one of the few cast members to appear in all eight seasons without a costume change of significance — the robes simply darkened.",
      "His 'little birds' were inherited by Qyburn after S5 — and turned to darker errands.",
      "The voice from the flames is one of the show's never-resolved mysteries.",
      "Varys is one of only three main characters who never wields a weapon on screen.",
      "His final scene removing his rings implies he attempted to poison Daenerys before his arrest.",
    ],
    keywords: ["spider", "little birds", "whisperers", "eunuch", "riddle", "realm", "spymaster", "essos"],
    sigil: "🕸️",
    accent: "cerulean",
  },
  {
    id: "brienne-of-tarth",
    name: "Brienne of Tarth",
    aliases: ["Brienne the Beauty (mockery)", "The Maid of Tarth"],
    titles: ["Ser — first woman knighted in Westerosi history", "Lord Commander of the Kingsguard"],
    house: "House Baratheon",
    affiliations: ["House Stark", "The Crown"],
    origin: "The Stormlands",
    seat: "Evenfall Hall, Tarth",
    alignment: "Lawful Honor",
    status: "Alive",
    actor: "Gwendoline Christie",
    firstAppearance: { season: 2, episode: 3, title: "What Is Dead May Never Die" },
    physical: { hair: "Straw blonde", eyes: "Astonishingly blue", build: "Towering, broader than most knights", distinguishing: "Carries Oathkeeper; bears a neck scar from the bear pit of Harrenhal" },
    biography: [
      "The only living child of the Evenstar of Tarth, Brienne grew up too tall, too strong, and too honest for a world that wanted ladies to be ornamental. Mocked as 'Brienne the Beauty' by suitors who courted her on a cruel bet, she answered the only way she ever would: she got better with a sword than all of them. She won a place in Renly Baratheon's Kingsguard by unhorsing Ser Loras Tyrell in a melee — and when Renly was murdered by a shadow in front of her, she was blamed, hunted, and bound to the only person who believed her: Catelyn Stark. Her oath to Catelyn — to return the Stark daughters — became the spine of her life.",
      "Assigned to escort Jaime Lannister to King's Landing, she dragged the realm's most cynical knight back toward honor: he lost a hand defending her from rape, leapt unarmed into a bear pit for her, and armed her with Oathkeeper. She kept every promise the war allowed — defeating the Hound in single combat over Arya, executing Stannis for Renly, arriving in the nick of time to save Sansa in the snow and swearing the sword to her at last. In Winterfell's great hall, on the eve of the Long Night, Jaime knighted her by firelight: the first woman knight in the history of the Seven Kingdoms. She ended the series as Lord Commander of Bran's Kingsguard — and finished Jaime's entry in the White Book herself, giving the Kingslayer the last word history denied him.",
    ],
    quote: "All my life men like you have sneered at me. And all my life I've been knocking men like you into the dust.",
    stats: {
      combat: 96, intellect: 60, loyalty: 100, influence: 55, survivability: 85, moralCompass: 97,
      screenTimeMinutes: 145, episodeCount: 42, debutYear: 2012, debutEpisode: "S2E3", namedKills: 12, loreMilestones: 8,
    },
    relationships: [
      { targetId: "jaime-lannister", kind: "ally", note: "He knighted her; she wrote his history" },
      { targetId: "sansa-stark", kind: "sworn-to", note: "The oath to Catelyn, finally fulfilled" },
      { targetId: "arya-stark", kind: "sworn-to", note: "Offered her sword; Arya chose her own path" },
      { targetId: "the-hound", kind: "rival", note: "Defeated him in single combat over Arya's custody" },
    ],
    timeline: [
      { marker: "S2E5", era: "S2 — Clash of Kings", title: "Renly's Death", description: "A shadow kills her king; she flees blamed for the murder.", pivotal: true },
      { marker: "S3E7", era: "S3 — Red Wedding Era", title: "The Bear Pit", description: "Fights a bear with a wooden sword; Jaime jumps in.", pivotal: true },
      { marker: "S4E8", era: "S4 — Lion's Fall", title: "Duel with the Hound", description: "Wins the most brutal one-on-one fight in the series.", pivotal: false },
      { marker: "S8E2", era: "S8 — The Last War", title: "Knighted by Jaime", description: "Ser Brienne of Tarth, first of her name.", pivotal: true },
      { marker: "S8E6", era: "S8 — The Last War", title: "Lord Commander", description: "Heads King Bran's Kingsguard; completes the White Book.", pivotal: true },
    ],
    trivia: [
      "Gwendoline Christie is 6'3\" — and trained extensively in sword work and horseback for the role.",
      "Her duel with the Hound was a show-only invention; they never meet in the books.",
      "Oathkeeper is forged from the melted Valyrian steel of Ned Stark's Ice.",
      "Her knighting scene was written specifically because fans had campaigned for it for years.",
      "She is the only character to have served Renly, Catelyn, Sansa, and Bran — and kept faith with all four.",
    ],
    keywords: ["oathkeeper", "knight", "tarth", "oath", "honor", "kingsguard", "first woman knighted"],
    sigil: "🛡️",
    accent: "cerulean",
  },
  {
    id: "the-hound",
    name: "Sandor Clegane",
    aliases: ["The Hound", "The Brother"],
    titles: ["Sworn shield to Joffrey Baratheon (renounced)"],
    house: "House Clegane",
    affiliations: ["The Crown", "Brotherhood Without Banners"],
    origin: "The Westerlands",
    seat: "Clegane's Keep",
    alignment: "Vengeful Justice",
    status: "Deceased",
    causeOfDeath: "Fell with his brother Gregor into the fires of the collapsing Red Keep — Cleganebowl",
    actor: "Rory McCann",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Dark, worn long over the left side", eyes: "Grey", build: "Massive — one of the largest fighters alive", distinguishing: "Severe burn scars covering the left side of his face since childhood" },
    biography: [
      "When Sandor Clegane was a boy, his older brother Gregor caught him playing with a discarded toy knight and held his face in a brazier of burning coals. Their father called it an accident; the burns and the lesson lasted a lifetime. Sandor grew into one of the deadliest swords in Westeros and its most honest cynic — a killer who refused knighthood because he had watched what knights actually were, sworn shield to a boy-king he openly despised. Fire remained the one thing on earth he feared.",
      "His long redemption ran through the Stark girls. To Sansa he was an unlikely guardian in Joffrey's court, the only man who told her the truth; he offered to take her north the night the Blackwater burned green and he deserted. With Arya — his hostage, then his student, then the closest thing to family he had — he crossed the war-torn Riverlands trading brutal lessons in survival, until Brienne broke him at the bloody hands of a cliff and Arya left him begging for death. He survived, found brief peace digging graves with a septon, lost it to raiders, fought beyond the Wall, and stood through the Long Night conquering his terror of fire to save Arya one last time. In the burning Red Keep he gave her the series' most important piece of advice — don't become me, go home — then climbed the stairs to meet his brother. The Mountain and the Hound fell together into the flames he'd feared since childhood.",
    ],
    quote: "Hate's as good a thing as any to keep a person going.",
    stats: {
      combat: 97, intellect: 58, loyalty: 75, influence: 40, survivability: 88, moralCompass: 62,
      screenTimeMinutes: 151, episodeCount: 47, debutYear: 2011, debutEpisode: "S1E1", namedKills: 25, loreMilestones: 9,
    },
    relationships: [
      { targetId: "arya-stark", kind: "apprentice", note: "His hostage turned protégé; she crossed him off her list" },
      { targetId: "sansa-stark", kind: "ally", note: "The little bird he could never quite abandon" },
      { targetId: "joffrey-baratheon", kind: "sworn-to", note: "Sworn shield until 'f— the king'", },
      { targetId: "brienne-of-tarth", kind: "rival", note: "Their cliff-edge duel nearly killed him" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Burned by Gregor", description: "His brother holds his face in the coals over a toy.", pivotal: true },
      { marker: "S2E9", era: "S2 — Clash of Kings", title: "Deserts at the Blackwater", description: "'F— the king.' Walks out of the burning battle.", pivotal: true },
      { marker: "S4E10", era: "S4 — Lion's Fall", title: "Left for Dead", description: "Beaten by Brienne; Arya walks away with his silver.", pivotal: true },
      { marker: "S8E3", era: "S8 — The Last War", title: "The Long Night", description: "Overcomes his fear of fire to shield Arya.", pivotal: false },
      { marker: "S8E5", era: "S8 — The Last War", title: "Cleganebowl", description: "Kills and dies with Gregor in the burning Red Keep.", pivotal: true },
    ],
    trivia: [
      "'Cleganebowl' was a fan meme for years before the show actually delivered it.",
      "Rory McCann was living in a tent and fishing for food when he was cast.",
      "The Hound's chicken scene at the Crossroads Inn is among the show's most quoted.",
      "He is one of the few characters to fight wights, men, and his own brother's reanimated corpse.",
      "His grave-digging interlude adapts a fan theory from the books about the 'gravedigger' on the Quiet Isle.",
    ],
    keywords: ["hound", "cleganebowl", "burns", "fire", "chicken", "mountain", "sworn shield"],
    sigil: "🐕",
    accent: "blood",
  },
  {
    id: "night-king",
    name: "The Night King",
    aliases: ["The Great Other's General (theory)", "The First White Walker"],
    titles: ["Lord of the Dead", "Commander of the Army of the Dead"],
    house: "Army of the Dead",
    affiliations: [],
    origin: "Beyond the Wall",
    seat: "The Lands of Always Winter",
    alignment: "Cold Entropy",
    status: "Deceased",
    causeOfDeath: "Shattered by Arya Stark's Valyrian steel dagger in the godswood of Winterfell",
    actor: "Vladimír Furdík (S6–S8); Richard Brake (S4–S5)",
    firstAppearance: { season: 4, episode: 4, title: "Oathkeeper" },
    physical: { hair: "None — crowned with horns of ice", eyes: "Glacial blue", build: "Tall, skeletal, armored in ice", distinguishing: "Spiral-scarred chest where the dragonglass entered; turns the dead with a raised arm" },
    biography: [
      "The Night King was not born — he was made. Millennia before the series, as the First Men's invasion devastated the weirwood groves, the Children of the Forest seized a captive man, bound him to a heart tree, and drove a shard of dragonglass into his chest. They wanted a weapon against humanity; what they created was an extinction. The first White Walker turned on Children and men alike, and the war that followed — the Long Night, a generation of darkness — ended only when he was driven into the uttermost north and the Wall was raised, laced with magic, to hold him there for eight thousand years.",
      "What returned in the series' opening scene was patience given form. He commanded through gesture alone: raising the dead of Hardhome in eerie silence as Jon Snow's boats pulled away, marking Bran Stark in a vision to break the magic of the Three-Eyed Raven's cave, spearing Viserion from the sky and raising the dragon as his own siege engine to bring down the Wall itself. His goal, as Bran framed it, was the murder of memory — to erase the world's record of itself by killing its living archive. He died feet from achieving it: in the godswood of Winterfell, his army victorious around him, his hand closing on Arya Stark's falling dagger an instant too late. When he shattered, every Walker and wight he had ever raised fell with him — eight thousand years of winter ending in a single drop of a knife.",
    ],
    quote: "(He has never spoken a single word on screen.)",
    stats: {
      combat: 99, intellect: 85, loyalty: 0, influence: 70, survivability: 98, moralCompass: 0,
      screenTimeMinutes: 35, episodeCount: 10, debutYear: 2014, debutEpisode: "S4E4", namedKills: 100000, loreMilestones: 7,
    },
    relationships: [
      { targetId: "arya-stark", kind: "killed-by", note: "The dagger drop that ended the Long Night" },
      { targetId: "bran-stark", kind: "enemy", note: "Marked him; hunted the world's memory" },
      { targetId: "jon-snow", kind: "enemy", note: "Locked eyes at Hardhome; the war's two poles" },
      { targetId: "daenerys-targaryen", kind: "enemy", note: "Killed and stole her dragon Viserion" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Created by the Children", description: "Dragonglass to the heart of a captive First Man.", pivotal: true },
      { marker: "S5E8", era: "S5 — Faith and Fire", title: "Hardhome", description: "Raises thousands of dead in view of Jon Snow.", pivotal: true },
      { marker: "S7E6", era: "S7 — The Great War Begins", title: "Kills Viserion", description: "An ice spear takes a dragon from the sky.", pivotal: true },
      { marker: "S7E7", era: "S7 — The Great War Begins", title: "The Wall Falls", description: "Undead Viserion's blue flame brings down Eastwatch.", pivotal: true },
      { marker: "S8E3", era: "S8 — The Last War", title: "Shattered at Winterfell", description: "Arya's dagger ends him and his entire army.", pivotal: true },
    ],
    trivia: [
      "Vladimír Furdík, who played him from S6, was previously the stuntman who performed the sword fights of other characters.",
      "The spiral patterns his army leaves mirror the Children of the Forest's sacred symbols — seen around the tree where he was made.",
      "He is immune to dragonfire — Drogon's full breath did not scratch him.",
      "The Night King of the show does not exist in the books; he is loosely inspired by the legendary 13th Lord Commander, the 'Night's King.'",
      "His smirk after surviving dragonfire is one of only two facial expressions he shows in the entire series.",
    ],
    keywords: ["white walker", "long night", "army of the dead", "winter", "wights", "ice", "hardhome", "viserion"],
    sigil: "❄️",
    accent: "cerulean",
  },
  {
    id: "robb-stark",
    name: "Robb Stark",
    aliases: ["The Young Wolf", "The King Who Lost the North"],
    titles: ["King in the North", "Lord of Winterfell"],
    house: "House Stark",
    affiliations: ["House Tully"],
    origin: "The North",
    seat: "Winterfell",
    alignment: "Lawful Honor",
    status: "Deceased",
    causeOfDeath: "Murdered at the Red Wedding by Roose Bolton — 'The Lannisters send their regards'",
    actor: "Richard Madden",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Auburn", eyes: "Blue", build: "Strong, young soldier-king", distinguishing: "Tully coloring; rode to war with the direwolf Grey Wind" },
    biography: [
      "Robb Stark was sixteen when his father's arrest made him the head of House Stark, and he answered like a story made flesh: he called the banners, marched south, and proceeded to win every single battle he ever fought. At the Whispering Wood he shattered Jaime Lannister's host and took the Kingslayer captive with a fraction of the losses; the North and the Riverlands crowned him on the spot — the first King in the North in three hundred years. Tywin Lannister, the realm's most feared commander, never beat him in the field. Not once.",
      "He lost the war everywhere else. He sent Theon Greyjoy to treat with the Iron Islands and got Winterfell burned for it. He executed Rickard Karstark for murdering captive boys — justice that cost him half his army. And he broke his marriage pact with Walder Frey for love of Talisa, a wound to Frey pride that Tywin's quill sharpened into a massacre. At the Twins, under the protection of guest right, the Rains of Castamere began to play: Talisa was stabbed through their unborn child, Catelyn's throat was cut, and Roose Bolton drove a dagger through the Young Wolf's heart with a personal message. The Freys sewed Grey Wind's head onto his corpse and paraded it — a desecration Arya Stark would repay in full, name by name.",
    ],
    quote: "I have won every battle, but I am losing this war.",
    stats: {
      combat: 85, intellect: 74, loyalty: 92, influence: 82, survivability: 25, moralCompass: 88,
      screenTimeMinutes: 100, episodeCount: 21, debutYear: 2011, debutEpisode: "S1E1", namedKills: 8, loreMilestones: 7,
    },
    relationships: [
      { targetId: "ned-stark", kind: "family", note: "Went to war to free him; arrived too late" },
      { targetId: "jon-snow", kind: "family", note: "Half-brothers in name; brothers in everything else" },
      { targetId: "tywin-lannister", kind: "enemy", note: "Unbeaten against him in the field; destroyed by his letters" },
      { targetId: "jaime-lannister", kind: "rival", note: "Captured him at the Whispering Wood" },
    ],
    timeline: [
      { marker: "S1E10", era: "S1 — The Wolf and the Lion", title: "Crowned King in the North", description: "'The King in the North!' echoes through Riverrun.", pivotal: true },
      { marker: "S2E4", era: "S2 — Clash of Kings", title: "Battle of Oxcross", description: "Grey Wind leads a rout of the Lannister camp.", pivotal: false },
      { marker: "S3E5", era: "S3 — Red Wedding Era", title: "Executes Karstark", description: "Justice over politics; the Karstarks abandon him.", pivotal: true },
      { marker: "S3E9", era: "S3 — Red Wedding Era", title: "The Red Wedding", description: "Murdered with his queen, mother, and army under guest right.", pivotal: true },
    ],
    trivia: [
      "Richard Madden was told about the Red Wedding when first cast — and kept the secret for three years.",
      "Robb never met Tyrion, Cersei, or Joffrey on screen after Season 1's Winterfell visit.",
      "The Red Wedding episode caused such audience trauma that reaction videos became a genre.",
      "Grey Wind tore out a man's throat at the Whispering Wood — battles often credited the wolf with dozens of kills.",
      "In the books his queen is Jeyne Westerling, who does not attend the wedding and survives.",
    ],
    keywords: ["young wolf", "king in the north", "red wedding", "grey wind", "whispering wood", "undefeated"],
    sigil: "⚔️",
    accent: "verdant",
  },
  {
    id: "joffrey-baratheon",
    name: "Joffrey Baratheon",
    aliases: ["Joffrey the Illborn", "The Boy King"],
    titles: ["King of the Andals and the First Men", "Lord of the Seven Kingdoms"],
    house: "House Baratheon",
    affiliations: ["House Lannister", "The Crown"],
    origin: "The Crownlands",
    seat: "Red Keep",
    alignment: "Ruthless Ambition",
    status: "Deceased",
    causeOfDeath: "Poisoned with the Strangler at his own wedding feast — the Purple Wedding",
    actor: "Jack Gleeson",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Golden blonde", eyes: "Green", build: "Slim, never a fighter", distinguishing: "Pouting Lannister features; died purple-faced clutching his throat" },
    biography: [
      "Joffrey was the lie at the center of the realm: presented to the world as Robert Baratheon's heir, he was in truth the firstborn of Cersei and Jaime Lannister's incest — the secret that killed Jon Arryn, then Robert, then Ned Stark. Crowned at thirteen, he revealed within one episode of his reign exactly what absolute power does to a cruel child: against every counsel, he ordered Ned Stark beheaded before the screaming crowd at the Sept of Baelor, single-handedly transforming a settled political crisis into a continental war.",
      "His reign was a catalogue of casual sadism — Sansa beaten by his Kingsguard and forced to view her father's head, crossbow executions in the throne room, the massacre of Robert's bastards — performed by a king who fled his own city's defense at the Blackwater. The realm's deliverance came dressed as a celebration. At his wedding to Margaery Tyrell, Joffrey gulped wine laced with the Strangler, smuggled in the stones of Sansa's necklace by Olenna Tyrell and Littlefinger, and died choking in his mother's arms while pointing at the uncle he'd spent the feast humiliating. His death launched Tyrion's trial, Tywin's fall, and Sansa's escape — meaning the Boy King's last act, like his first, set the realm on fire.",
    ],
    quote: "Everyone is mine to torment.",
    stats: {
      combat: 10, intellect: 35, loyalty: 15, influence: 75, survivability: 20, moralCompass: 3,
      screenTimeMinutes: 110, episodeCount: 26, debutYear: 2011, debutEpisode: "S1E1", namedKills: 5, loreMilestones: 6,
    },
    relationships: [
      { targetId: "cersei-lannister", kind: "family", note: "The mother who indulged the monster" },
      { targetId: "jaime-lannister", kind: "family", note: "Father in truth, 'uncle' in name" },
      { targetId: "sansa-stark", kind: "enemy", note: "His betrothed, hostage, and favorite victim" },
      { targetId: "ned-stark", kind: "killer-of", note: "Ordered the execution that ignited the war" },
      { targetId: "petyr-baelish", kind: "killed-by", note: "Co-architect of the Purple Wedding" },
      { targetId: "tyrion-lannister", kind: "rival", note: "The uncle who slapped him — thrice — and was framed for his murder" },
    ],
    timeline: [
      { marker: "S1E9", era: "S1 — The Wolf and the Lion", title: "Orders Ned's Execution", description: "One sentence from a boy-king starts the War of the Five Kings.", pivotal: true },
      { marker: "S2E9", era: "S2 — Clash of Kings", title: "Flees the Blackwater", description: "Abandons the walls mid-battle at Cersei's summons.", pivotal: false },
      { marker: "S4E2", era: "S4 — Lion's Fall", title: "The Purple Wedding", description: "Dies choking at his own feast.", pivotal: true },
    ],
    trivia: [
      "Jack Gleeson largely retired from acting after the role, returning to academia.",
      "Gleeson is reportedly one of the kindest cast members — fans famously struggled to separate actor from role.",
      "Joffrey renamed the Valyrian sword Tywin gave him 'Widow's Wail' — forged from Ned Stark's Ice.",
      "George R.R. Martin has confirmed Olenna Tyrell as the poisoner, with Littlefinger as logistics.",
    ],
    keywords: ["boy king", "purple wedding", "strangler", "tyrant", "incest", "crossbow", "widow's wail"],
    sigil: "🍷",
    accent: "amber",
  },
  {
    id: "ramsay-bolton",
    name: "Ramsay Bolton",
    aliases: ["Ramsay Snow", "The Bastard of Bolton", "The Bastard of the Dreadfort"],
    titles: ["Lord of Winterfell (by conquest)", "Warden of the North (claimed)"],
    house: "House Bolton",
    affiliations: [],
    origin: "The North",
    seat: "The Dreadfort / Winterfell",
    alignment: "Chaotic Schemer",
    status: "Deceased",
    causeOfDeath: "Eaten alive by his own starving hounds, on Sansa Stark's arrangement",
    actor: "Iwan Rheon",
    firstAppearance: { season: 3, episode: 2, title: "Dark Wings, Dark Words" },
    physical: { hair: "Dark, curly", eyes: "Pale blue", build: "Wiry, deceptively quick", distinguishing: "A flayed-man grin; fights dirty by preference and principle" },
    biography: [
      "Ramsay Snow was the acknowledged bastard of Roose Bolton, lord of a house whose sigil is a flayed man and whose words are 'Our Blades Are Sharp.' He spent the series proving the sigil was a family portrait. Introduced as an anonymous 'helper' to the captive Theon Greyjoy, he conducted the show's most extended psychological destruction — flaying, mutilation, and mind-games that dismantled Theon into the creature called Reek — all before the audience even learned his name.",
      "Legitimized by royal decree as payment for the Red Wedding, Ramsay seized the Stark legacy through marriage to Sansa, whose wedding-night abuse marked the show's darkest controversy and her hardest steel. He murdered his father when Roose's trueborn son was born, fed his stepmother and infant half-brother to the hounds, and shot Rickon Stark dead with arrows in the opening of the Battle of the Bastards — the cruelty designed to bait Jon Snow into breaking formation, which worked. It was his only strategic miscalculation that mattered: the Vale's knights crushed his army, Jon beat him nearly to death with bare fists in the Winterfell courtyard, and Sansa granted him a perfectly symmetrical end — locked in his own kennels with the hounds he had starved for seven days. 'Your words will disappear. Your house will disappear. All memory of you will disappear.'",
    ],
    quote: "If you think this has a happy ending, you haven't been paying attention.",
    stats: {
      combat: 80, intellect: 70, loyalty: 5, influence: 45, survivability: 55, moralCompass: 1,
      screenTimeMinutes: 90, episodeCount: 25, debutYear: 2013, debutEpisode: "S3E2", namedKills: 14, loreMilestones: 6,
    },
    relationships: [
      { targetId: "sansa-stark", kind: "spouse", note: "His victim, then his executioner" },
      { targetId: "jon-snow", kind: "enemy", note: "Beaten down in the mud of Winterfell's yard" },
      { targetId: "robb-stark", kind: "enemy", note: "The Boltons' knife in the Red Wedding" },
    ],
    timeline: [
      { marker: "S3E10", era: "S3 — Red Wedding Era", title: "Reek", description: "Completes Theon Greyjoy's psychological destruction.", pivotal: true },
      { marker: "S5E6", era: "S5 — Faith and Fire", title: "Marries Sansa Stark", description: "The Bolton claim on the North, sealed in cruelty.", pivotal: true },
      { marker: "S6E2", era: "S6 — Winds of Winter", title: "Kills Roose Bolton", description: "Patricide by dagger; feeds the heirs to the hounds.", pivotal: true },
      { marker: "S6E9", era: "S6 — Winds of Winter", title: "Battle of the Bastards", description: "Loses the North; meets his hounds.", pivotal: true },
    ],
    trivia: [
      "Iwan Rheon was the runner-up for the role of Jon Snow.",
      "Ramsay's hounds were played by trained dogs who reportedly adored Rheon between takes.",
      "His 'twenty good men' raid on Stannis's camp became shorthand for the show's later plot armor debates.",
      "House Bolton's extinction fulfilled Sansa's sentence verbatim: their words, house, and memory erased.",
    ],
    keywords: ["bastard of bolton", "reek", "flayed man", "hounds", "dreadfort", "sadist", "battle of the bastards"],
    sigil: "🔪",
    accent: "blood",
  },
  {
    id: "ygritte",
    name: "Ygritte",
    aliases: ["The Wildling Girl"],
    titles: ["Spearwife of the Free Folk"],
    house: "Free Folk",
    affiliations: [],
    origin: "Beyond the Wall",
    seat: "None — 'we do not kneel'",
    alignment: "Protective Loyalty",
    status: "Deceased",
    causeOfDeath: "Shot through the heart by Olly during the Battle of Castle Black; died in Jon's arms",
    actor: "Rose Leslie",
    firstAppearance: { season: 2, episode: 6, title: "The Old Gods and the New" },
    physical: { hair: "Red — 'kissed by fire,' lucky among the free folk", eyes: "Blue-grey", build: "Compact, quick archer", distinguishing: "Carried a recurve bow; gap-toothed grin" },
    biography: [
      "Ygritte was a spearwife of the free folk, born to the hard country beyond the Wall where no man kneels and no name is given that isn't earned. Captured by Jon Snow's ranging party, she should have died on his sword — and read in his hesitation everything she needed to know about him. Marched as his prisoner, she talked, taunted, and tested him into the truth, then led him into Mance Rayder's host when the capture reversed. Her refrain — 'You know nothing, Jon Snow' — began as mockery and ended as the truest sentence anyone ever said to him.",
      "She was Jon's first love and the embodiment of the free folk's case against the south: fierce, unsentimental, and freer in a frozen wasteland than any kneeler in a castle. They broke his vows together in the grotto beneath the Wall; when he abandoned her to return to his Watch, the arrow she put in his back was both punishment and mercy — three arrows, none fatal, from the best archer in the host. At the Battle of Castle Black they met across the burning yard one last time. The boy Olly's arrow found her heart mid-hesitation, and she died in Jon's arms wishing they had never left the cave. Jon burned her beyond the Wall, in the free air she came from.",
    ],
    quote: "You know nothing, Jon Snow.",
    stats: {
      combat: 78, intellect: 55, loyalty: 88, influence: 30, survivability: 50, moralCompass: 72,
      screenTimeMinutes: 60, episodeCount: 17, debutYear: 2012, debutEpisode: "S2E6", namedKills: 9, loreMilestones: 4,
    },
    relationships: [
      { targetId: "jon-snow", kind: "lover", note: "The vow he broke; the loss that hardened him" },
    ],
    timeline: [
      { marker: "S2E6", era: "S2 — Clash of Kings", title: "Captured by Jon Snow", description: "He cannot execute her; the rope between them begins.", pivotal: true },
      { marker: "S3E6", era: "S3 — Red Wedding Era", title: "Climbs the Wall", description: "Saved by Jon mid-avalanche; they see the world from the top.", pivotal: false },
      { marker: "S3E10", era: "S3 — Red Wedding Era", title: "Three Arrows", description: "Shoots the man she loves rather than let him leave a liar.", pivotal: true },
      { marker: "S4E9", era: "S4 — Lion's Fall", title: "Dies at Castle Black", description: "Olly's arrow; the cave, never left, never forgotten.", pivotal: true },
    ],
    trivia: [
      "Rose Leslie and Kit Harington met on the show and married in real life in 2018.",
      "'Kissed by fire' — red hair — is considered lucky by the free folk.",
      "Her line 'You know nothing, Jon Snow' appears in the books as a constant refrain of his memory.",
      "She claimed Castle Black's well-armed knights feared the free folk because 'we're free.'",
    ],
    keywords: ["wildling", "free folk", "kissed by fire", "you know nothing", "archer", "castle black"],
    sigil: "🏹",
    accent: "blood",
  },
  {
    id: "viserys-targaryen",
    name: "Viserys Targaryen",
    aliases: ["The Beggar King", "The Last Dragon (self-styled)"],
    titles: ["King of the Andals and the First Men (claimed, in exile)"],
    house: "House Targaryen",
    affiliations: [],
    origin: "The Crownlands",
    seat: "None — exile in Essos",
    alignment: "Ruthless Ambition",
    status: "Deceased",
    causeOfDeath: "'Crowned' with molten gold by Khal Drogo in Vaes Dothrak",
    actor: "Harry Lloyd",
    firstAppearance: { season: 1, episode: 1, title: "Winter Is Coming" },
    physical: { hair: "Silver-gold", eyes: "Lilac", build: "Slender, unmartial", distinguishing: "Classic Valyrian beauty curdled by entitlement" },
    biography: [
      "Viserys was eight years old when his world was annihilated — his father butchered on the throne-room floor, his family's dynasty ended, his pregnant mother dying in a storm as he and the newborn Daenerys were smuggled into exile. He spent the next seventeen years sliding from honored guest to mocked beggar across the Free Cities, selling his mother's crown and feeding on a single fantasy: that Westeros was sewing dragon banners and drinking secret toasts to its king across the water. The fantasy was a lie, and somewhere in the long humiliation, whatever was salvageable in him rotted into his father's madness — 'waking the dragon,' he called his rages, mistaking cruelty for fire.",
      "His one transaction of consequence was selling his sister. Trading Daenerys to Khal Drogo for the promise of an army, he then watched with mounting horror as the asset became a queen: the khalasar followed her, loved her, protected her — from him. Drunk in the sacred city of Vaes Dothrak, where blades are forbidden, he drew a sword on his pregnant sister and demanded his crown. Drogo gave him one: a belt of gold, melted in a stewpot, poured over his head. Daenerys watched without flinching and delivered his epitaph — 'He was no dragon. Fire cannot kill a dragon.' His death freed her to become everything he pretended to be.",
    ],
    quote: "I would let his whole tribe f— you, all forty thousand men and their horses too, if that's what it took.",
    stats: {
      combat: 15, intellect: 40, loyalty: 10, influence: 25, survivability: 12, moralCompass: 15,
      screenTimeMinutes: 35, episodeCount: 5, debutYear: 2011, debutEpisode: "S1E1", namedKills: 0, loreMilestones: 3,
    },
    relationships: [
      { targetId: "daenerys-targaryen", kind: "family", note: "Sold her for a crown; received one of molten gold" },
    ],
    timeline: [
      { marker: "PRE", era: "Before the Series", title: "Exile to Essos", description: "Smuggled to Braavos as the dynasty falls.", pivotal: true },
      { marker: "S1E1", era: "S1 — The Wolf and the Lion", title: "Sells Daenerys to Drogo", description: "A sister for an army.", pivotal: true },
      { marker: "S1E6", era: "S1 — The Wolf and the Lion", title: "A Golden Crown", description: "Drogo crowns the Beggar King in molten gold.", pivotal: true },
    ],
    trivia: [
      "Harry Lloyd is the great-great-great-grandson of Charles Dickens.",
      "The molten gold effect used heated syrup and clever editing — no CGI for the pour itself.",
      "Viserys's account of selling their mother's crown is one of the rare moments the show grants him pathos.",
      "His death scene was Emilia Clarke's audition centerpiece for conveying Dany's transformation.",
    ],
    keywords: ["beggar king", "golden crown", "exile", "targaryen", "madness", "wake the dragon"],
    sigil: "🫅",
    accent: "amber",
  }
];

/** Aggregate metadata for SEO copy and dashboard counters */
export const DB_META = {
  totalProfiles: CHARACTERS.length,
  totalTimelineEvents: CHARACTERS.reduce((n, c) => n + c.timeline.length, 0),
  totalRelationships: CHARACTERS.reduce((n, c) => n + c.relationships.length, 0),
  totalTriviaFacts: CHARACTERS.reduce((n, c) => n + c.trivia.length, 0),
};

export const byId = (id: string) => CHARACTERS.find((c) => c.id === id);

